#! /bin/sh
### BEGIN INIT INFO
# Provides:          api_site
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: api_site
# Description:       ADA
### END INIT INFO
#
# Author:      WTI
#


set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/opt/API_site
SL_PATH=/opt/API_site
DAEMON="/opt/API_site/api_site.py "
PIDFILE=/var/run/ada_api.pid

test -x $SL_PATH || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting deferred execution api_site"
	start_daemon -p $PIDFILE $DAEMON
	#sudo $DAEMON
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping deferred execution api_site"
        killproc -p $PIDFILE $DAEMON
	#sudo ada_api_stop
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/api_site {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
